### ISSUE TITLE
Função não conhecida printplot

### ISSUE THREAD

**Issue by mrmodolo** [cleuton/datascience#2]
Cleuton,

Encontrei uma função (printplot) no script de sua primeira lição que não consegui localizar em nenhuma biblioteca.
Será que não é um erro de grafia?
printplot(summary(df))

Abraços,
Marcelo Módolo

**Comment by cleuton** [comment]
Com certeza

Em seg, 19 de mar de 2018 18:08, Marcelo Rezende Módolo <
notifications@github.com> escreveu:
