### ISSUE TITLE
capt4.ipynb

### ISSUE THREAD

**Issue by Igormagno13** [cleuton/datascience#3]
Rodei o notebook do capt4 pelo Google Colab e na linha 30 abaixo

plt.hist(data, bins=25, normed=True, alpha=0.6)
xmin, xmax = plt.xlim()
x = np.linspace(xmin, xmax, 100)
p = norm.pdf(x, mu, std)
plt.plot(x, p, 'k', linewidth=2)
title = "Fit results: mu = %.2f,  std = %.2f" % (mu, std)
plt.title(title)

plt.show()

está aparecendo o seguinte erro:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-30-e8576afb7d9d> in <module>()
----> 1 plt.hist(data, bins=25, normed=True, alpha=0.6)
      2 xmin, xmax = plt.xlim()
      3 x = np.linspace(xmin, xmax, 100)
      4 p = norm.pdf(x, mu, std)
      5 plt.plot(x, p, 'k', linewidth=2)

5 frames
/usr/local/lib/python3.6/dist-packages/matplotlib/artist.py in _update_property(self, k, v)
   1000                 if not callable(func):
   1001                     raise AttributeError('{!r} object has no property {!r}'
-> 1002                                          .format(type(self).__name__, k))
   1003                 return func(v)
   1004 

AttributeError: 'Rectangle' object has no property 'normed'

**Comment by cleuton** [comment]
Olá! Consultei a função "hist", do matplotlib plt, e o atributo **normed** constava como **deprecated**. Você deve estar utilizando uma versão mais nova. A recomendação é substituir por **density=True**. Veja aqui: https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.hist.html
